// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciatjyyssskjbuuiqacy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpYXRqeXlzc3NramJ1dWlxYWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODk5NDksImV4cCI6MjA2ODc2NTk0OX0.4yStrmz96Hht7m1LJTR7Z2ljnq1WkiHY4uTswNCuCeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});